import { PrismaClient, CourtType, CourtSurface } from '@prisma/client';

const prisma = new PrismaClient();

const courts = [
  {
    name: 'Парк Азамат',
    slug: 'park-azamat',
    address: 'Парк Азамат, Юнусабадский район',
    district: 'Юнусабадский',
    city: 'Ташкент',
    latitude: 41.365237,
    longitude: 69.389336,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в парке Азамат. Удобное расположение рядом со станцией Яланғоч.',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Баскетбольная площадка, ул. Хамзы',
    slug: 'court-hamza-street',
    address: 'ул. Хамзы, Шайхантахурский район',
    district: 'Шайхантахурский',
    city: 'Ташкент',
    latitude: 41.306048,
    longitude: 69.296793,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Шайхантахурском районе.',
    isVerified: false,
    isActive: true,
  },
  {
    name: 'Vosiq International School',
    slug: 'vosiq-international-school',
    address: 'Юнусабадский район, махалля Увайсий',
    district: 'Юнусабадский',
    city: 'Ташкент',
    latitude: 41.373594,
    longitude: 69.313267,
    type: CourtType.INDOOR,
    surface: CourtSurface.HARDWOOD,
    isFree: false,
    hasLighting: true,
    hasChangingRooms: true,
    hoops: 2,
    description: 'Спортивный зал школы Vosiq International School. Паркетное покрытие, закрытый зал.',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Баскетбольный корт, Юнусабад',
    slug: 'court-yunusabad',
    address: 'Юнусабадский район',
    district: 'Юнусабадский',
    city: 'Ташкент',
    latitude: 41.340969,
    longitude: 69.289116,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Юнусабадском районе.',
    isVerified: false,
    isActive: true,
  },
  {
    name: 'Баскетбольный корт, Чиланзар (1)',
    slug: 'court-chilanzar-1',
    address: 'Чиланзарский район',
    district: 'Чиланзарский',
    city: 'Ташкент',
    latitude: 41.330788,
    longitude: 69.278931,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Чиланзарском районе.',
    isVerified: false,
    isActive: true,
  },
  {
    name: 'Баскетбольный корт, Чиланзар (2)',
    slug: 'court-chilanzar-2',
    address: 'Чиланзарский район',
    district: 'Чиланзарский',
    city: 'Ташкент',
    latitude: 41.330472,
    longitude: 69.279145,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Чиланзарском районе.',
    isVerified: false,
    isActive: true,
  },
  {
    name: 'Баскетбольный корт, Чиланзар (3)',
    slug: 'court-chilanzar-3',
    address: 'Чиланзарский район',
    district: 'Чиланзарский',
    city: 'Ташкент',
    latitude: 41.326251,
    longitude: 69.278917,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Чиланзарском районе.',
    isVerified: false,
    isActive: true,
  },
  {
    name: 'Баскетбольный корт, Шайхантахур',
    slug: 'court-shaykhantakhur',
    address: 'Шайхантахурский район',
    district: 'Шайхантахурский',
    city: 'Ташкент',
    latitude: 41.312673,
    longitude: 69.286375,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Шайхантахурском районе.',
    isVerified: false,
    isActive: true,
  },
  {
    name: 'Баскетбольная площадка, Мирабад',
    slug: 'court-mirabad',
    address: 'Мирабадский район, махалля Мингурик',
    district: 'Мирабадский',
    city: 'Ташкент',
    latitude: 41.306619,
    longitude: 69.282774,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый баскетбольный корт в Мирабадском районе, махалля Мингурик.',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Спортивная площадка, Бешагач',
    slug: 'court-beshagach',
    address: 'Чиланзарский район, махалля Бешагач',
    district: 'Чиланзарский',
    city: 'Ташкент',
    latitude: 41.307654,
    longitude: 69.254345,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Открытый спортивный корт в махалле Бешагач, Чиланзарский район.',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Корт при Геодезическом техникуме',
    slug: 'court-geodesy-technikum',
    address: 'ул. Мирзо-Улугбекская, 82, Мирзо-Улугбекский район',
    district: 'Мирзо-Улугбекский',
    city: 'Ташкент',
    latitude: 41.345216,
    longitude: 69.348911,
    type: CourtType.OUTDOOR,
    surface: CourtSurface.ASPHALT,
    isFree: true,
    hasLighting: false,
    hasChangingRooms: false,
    hoops: 2,
    description: 'Баскетбольный корт при Ташкентском геодезическом и картографическом техникуме. Ул. Мирзо-Улугбекская, 82.',
    isVerified: true,
    isActive: true,
  },
];

async function main() {
  console.log('Seeding 11 new courts...');
  for (const court of courts) {
    await prisma.court.upsert({
      where: { slug: court.slug },
      update: court,
      create: court,
    });
    console.log(`  ✓ ${court.name}`);
  }
  console.log(`Done! Total courts: ${await prisma.court.count()}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
